version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"

  chik:
    image: chiknetwork/chik-docker:latest
    container_name: chik
    restart: unless-stopped
    ports:
      - "9678:9678"
    expose:
      - 56634
      - 9789
      - 9791
      - 9793
      - 9794
      - 9796
      - 10490
    environment:
      self_hostname: 0.0.0.0
    volumes:
      - chik-root:/root/.chik

  chik-exporter:
    image: ghcr.io/chik-network/chik-exporter:latest
    container_name: chik-exporter
    restart: unless-stopped
    environment:
      CHIK_ROOT: /root/.chik/mainnet
      CHIK_EXPORTER_HOSTNAME: chik
    volumes:
      - chik-root:/root/.chik

volumes:
  chik-root:
